// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Rainsoft.Proto {

  /// <summary>Holder for reflection information generated from Common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for Common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxDb21tb24ucHJvdG8SEmNvbS5yYWluc29mdC5wcm90byIxCg5Db21tb25S",
            "ZXNwb25zZRIOCgZzdGF0dXMYASABKAUSDwoHbWVzc2FnZRgCIAEoCSKXAgoR",
            "Q29tbW9uUmVxdWVzdEluZm8SEgoKcGhvbmVfbmFtZRgBIAEoCRIUCgxwaG9u",
            "ZV9zeXN0ZW0YAiABKAkSEwoLcGhvbmVfbW9kZWwYAyABKAkSFwoPcGhvbmVf",
            "cHJvZHVjdGVyGAQgASgJEhMKC2FwcF92ZXJzaW9uGAUgASgJEhEKCXBob25l",
            "X21hYxgGIAEoCRISCgpwaG9uZV9pbWVpGAcgASgJEhAKCHBob25lX2lwGAgg",
            "ASgJEg8KB3VzZXJfaWQYCSABKAkSEgoKcGxhY2VfY29kZRgKIAEoCRIQCghh",
            "cHBfY29kZRgLIAEoCRIRCgl1c2VyX3R5cGUYDCABKAkSEgoKdGltZXN0YW1w",
            "cxgNIAEoEEInChJjb20ucmFpbnNvZnQucHJvdG9CC0NvbW1vblByb3RvogID",
            "UVlUYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Rainsoft.Proto.CommonResponse), global::Com.Rainsoft.Proto.CommonResponse.Parser, new[]{ "Status", "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Rainsoft.Proto.CommonRequestInfo), global::Com.Rainsoft.Proto.CommonRequestInfo.Parser, new[]{ "PhoneName", "PhoneSystem", "PhoneModel", "PhoneProducter", "AppVersion", "PhoneMac", "PhoneImei", "PhoneIp", "UserId", "PlaceCode", "AppCode", "UserType", "Timestamps" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///返回的数据如果只有status 和 message 使用这个通用的response
  /// </summary>
  public sealed partial class CommonResponse : pb::IMessage<CommonResponse> {
    private static readonly pb::MessageParser<CommonResponse> _parser = new pb::MessageParser<CommonResponse>(() => new CommonResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CommonResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Rainsoft.Proto.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonResponse(CommonResponse other) : this() {
      status_ = other.status_;
      message_ = other.message_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonResponse Clone() {
      return new CommonResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private int status_;
    /// <summary>
    ///返回状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    /// <summary>
    ///返回消息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CommonResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CommonResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (Message != other.Message) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != 0) hash ^= Status.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Status);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Status);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CommonResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Status = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 每个request都需要的信息
  /// </summary>
  public sealed partial class CommonRequestInfo : pb::IMessage<CommonRequestInfo> {
    private static readonly pb::MessageParser<CommonRequestInfo> _parser = new pb::MessageParser<CommonRequestInfo>(() => new CommonRequestInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CommonRequestInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Rainsoft.Proto.CommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonRequestInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonRequestInfo(CommonRequestInfo other) : this() {
      phoneName_ = other.phoneName_;
      phoneSystem_ = other.phoneSystem_;
      phoneModel_ = other.phoneModel_;
      phoneProducter_ = other.phoneProducter_;
      appVersion_ = other.appVersion_;
      phoneMac_ = other.phoneMac_;
      phoneImei_ = other.phoneImei_;
      phoneIp_ = other.phoneIp_;
      userId_ = other.userId_;
      placeCode_ = other.placeCode_;
      appCode_ = other.appCode_;
      userType_ = other.userType_;
      timestamps_ = other.timestamps_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonRequestInfo Clone() {
      return new CommonRequestInfo(this);
    }

    /// <summary>Field number for the "phone_name" field.</summary>
    public const int PhoneNameFieldNumber = 1;
    private string phoneName_ = "";
    /// <summary>
    ///手机名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PhoneName {
      get { return phoneName_; }
      set {
        phoneName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_system" field.</summary>
    public const int PhoneSystemFieldNumber = 2;
    private string phoneSystem_ = "";
    /// <summary>
    ///手机操作系统 例如 iOS10.3
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PhoneSystem {
      get { return phoneSystem_; }
      set {
        phoneSystem_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_model" field.</summary>
    public const int PhoneModelFieldNumber = 3;
    private string phoneModel_ = "";
    /// <summary>
    ///手机型号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PhoneModel {
      get { return phoneModel_; }
      set {
        phoneModel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_producter" field.</summary>
    public const int PhoneProducterFieldNumber = 4;
    private string phoneProducter_ = "";
    /// <summary>
    ///手机制造商
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PhoneProducter {
      get { return phoneProducter_; }
      set {
        phoneProducter_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "app_version" field.</summary>
    public const int AppVersionFieldNumber = 5;
    private string appVersion_ = "";
    /// <summary>
    ///app版本号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AppVersion {
      get { return appVersion_; }
      set {
        appVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_mac" field.</summary>
    public const int PhoneMacFieldNumber = 6;
    private string phoneMac_ = "";
    /// <summary>
    ///手机mac地址
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PhoneMac {
      get { return phoneMac_; }
      set {
        phoneMac_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_imei" field.</summary>
    public const int PhoneImeiFieldNumber = 7;
    private string phoneImei_ = "";
    /// <summary>
    ///手机imei
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PhoneImei {
      get { return phoneImei_; }
      set {
        phoneImei_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_ip" field.</summary>
    public const int PhoneIpFieldNumber = 8;
    private string phoneIp_ = "";
    /// <summary>
    ///手机ip地址
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PhoneIp {
      get { return phoneIp_; }
      set {
        phoneIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 9;
    private string userId_ = "";
    /// <summary>
    ///用户id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "place_code" field.</summary>
    public const int PlaceCodeFieldNumber = 10;
    private string placeCode_ = "";
    /// <summary>
    ///场所id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PlaceCode {
      get { return placeCode_; }
      set {
        placeCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "app_code" field.</summary>
    public const int AppCodeFieldNumber = 11;
    private string appCode_ = "";
    /// <summary>
    ///app类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AppCode {
      get { return appCode_; }
      set {
        appCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_type" field.</summary>
    public const int UserTypeFieldNumber = 12;
    private string userType_ = "";
    /// <summary>
    ///用户类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserType {
      get { return userType_; }
      set {
        userType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamps" field.</summary>
    public const int TimestampsFieldNumber = 13;
    private long timestamps_;
    /// <summary>
    ///时间戳
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Timestamps {
      get { return timestamps_; }
      set {
        timestamps_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CommonRequestInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CommonRequestInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PhoneName != other.PhoneName) return false;
      if (PhoneSystem != other.PhoneSystem) return false;
      if (PhoneModel != other.PhoneModel) return false;
      if (PhoneProducter != other.PhoneProducter) return false;
      if (AppVersion != other.AppVersion) return false;
      if (PhoneMac != other.PhoneMac) return false;
      if (PhoneImei != other.PhoneImei) return false;
      if (PhoneIp != other.PhoneIp) return false;
      if (UserId != other.UserId) return false;
      if (PlaceCode != other.PlaceCode) return false;
      if (AppCode != other.AppCode) return false;
      if (UserType != other.UserType) return false;
      if (Timestamps != other.Timestamps) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PhoneName.Length != 0) hash ^= PhoneName.GetHashCode();
      if (PhoneSystem.Length != 0) hash ^= PhoneSystem.GetHashCode();
      if (PhoneModel.Length != 0) hash ^= PhoneModel.GetHashCode();
      if (PhoneProducter.Length != 0) hash ^= PhoneProducter.GetHashCode();
      if (AppVersion.Length != 0) hash ^= AppVersion.GetHashCode();
      if (PhoneMac.Length != 0) hash ^= PhoneMac.GetHashCode();
      if (PhoneImei.Length != 0) hash ^= PhoneImei.GetHashCode();
      if (PhoneIp.Length != 0) hash ^= PhoneIp.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (PlaceCode.Length != 0) hash ^= PlaceCode.GetHashCode();
      if (AppCode.Length != 0) hash ^= AppCode.GetHashCode();
      if (UserType.Length != 0) hash ^= UserType.GetHashCode();
      if (Timestamps != 0L) hash ^= Timestamps.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PhoneName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PhoneName);
      }
      if (PhoneSystem.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PhoneSystem);
      }
      if (PhoneModel.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PhoneModel);
      }
      if (PhoneProducter.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PhoneProducter);
      }
      if (AppVersion.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AppVersion);
      }
      if (PhoneMac.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PhoneMac);
      }
      if (PhoneImei.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(PhoneImei);
      }
      if (PhoneIp.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(PhoneIp);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(UserId);
      }
      if (PlaceCode.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(PlaceCode);
      }
      if (AppCode.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(AppCode);
      }
      if (UserType.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(UserType);
      }
      if (Timestamps != 0L) {
        output.WriteRawTag(105);
        output.WriteSFixed64(Timestamps);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PhoneName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneName);
      }
      if (PhoneSystem.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneSystem);
      }
      if (PhoneModel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneModel);
      }
      if (PhoneProducter.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneProducter);
      }
      if (AppVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppVersion);
      }
      if (PhoneMac.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneMac);
      }
      if (PhoneImei.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneImei);
      }
      if (PhoneIp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneIp);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (PlaceCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlaceCode);
      }
      if (AppCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppCode);
      }
      if (UserType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserType);
      }
      if (Timestamps != 0L) {
        size += 1 + 8;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CommonRequestInfo other) {
      if (other == null) {
        return;
      }
      if (other.PhoneName.Length != 0) {
        PhoneName = other.PhoneName;
      }
      if (other.PhoneSystem.Length != 0) {
        PhoneSystem = other.PhoneSystem;
      }
      if (other.PhoneModel.Length != 0) {
        PhoneModel = other.PhoneModel;
      }
      if (other.PhoneProducter.Length != 0) {
        PhoneProducter = other.PhoneProducter;
      }
      if (other.AppVersion.Length != 0) {
        AppVersion = other.AppVersion;
      }
      if (other.PhoneMac.Length != 0) {
        PhoneMac = other.PhoneMac;
      }
      if (other.PhoneImei.Length != 0) {
        PhoneImei = other.PhoneImei;
      }
      if (other.PhoneIp.Length != 0) {
        PhoneIp = other.PhoneIp;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.PlaceCode.Length != 0) {
        PlaceCode = other.PlaceCode;
      }
      if (other.AppCode.Length != 0) {
        AppCode = other.AppCode;
      }
      if (other.UserType.Length != 0) {
        UserType = other.UserType;
      }
      if (other.Timestamps != 0L) {
        Timestamps = other.Timestamps;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            PhoneName = input.ReadString();
            break;
          }
          case 18: {
            PhoneSystem = input.ReadString();
            break;
          }
          case 26: {
            PhoneModel = input.ReadString();
            break;
          }
          case 34: {
            PhoneProducter = input.ReadString();
            break;
          }
          case 42: {
            AppVersion = input.ReadString();
            break;
          }
          case 50: {
            PhoneMac = input.ReadString();
            break;
          }
          case 58: {
            PhoneImei = input.ReadString();
            break;
          }
          case 66: {
            PhoneIp = input.ReadString();
            break;
          }
          case 74: {
            UserId = input.ReadString();
            break;
          }
          case 82: {
            PlaceCode = input.ReadString();
            break;
          }
          case 90: {
            AppCode = input.ReadString();
            break;
          }
          case 98: {
            UserType = input.ReadString();
            break;
          }
          case 105: {
            Timestamps = input.ReadSFixed64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
